[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# PostgreSQL Database Service
[[services]]
name = "postgres-db"
source = "postgresql"

[services.variables]
POSTGRES_USER = "opa_user"
POSTGRES_PASSWORD = "${{ railway.database.password }}"
POSTGRES_DB = "opa_zero_poll"

# Data Provider API Service
[[services]]
name = "data-provider-api"
source = "new-architecture/components/data-provider-api"

[services.variables]
PORT = "8110"
DEBUG = "false"
WEBHOOK_SECRET = "railway_super_secret_key_2025"
DISABLE_JWT_VALIDATION = "true"
# Database connection - będzie automatycznie połączone z PostgreSQL service
DB_HOST = "${{ services.postgres-db.host }}"
DB_PORT = "5432"
DB_USER = "opa_user"
DB_PASSWORD = "${{ services.postgres-db.POSTGRES_PASSWORD }}"
DB_NAME = "opa_zero_poll"

[services.healthcheck]
path = "/health"
timeout = 30

# Next.js Frontend Service (już istniejący)
[[services]]
name = "frontend"
source = "."

[services.variables]
# TODO: Zamień na faktyczny URL z Railway dashboard
DATA_PROVIDER_API_URL = "opa-zero-poll-production-1934.up.railway.app" 